"""Update event and period tables structures

Revision ID: 40950b5ee32e
Revises: c3eeb1807b88
Create Date: 2025-04-17 00:09:18.203574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40950b5ee32e'
down_revision: Union[str, None] = 'c3eeb1807b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'coordinates', ['id'])
    op.add_column('event', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('event', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'memeberstatuss', ['id'])
    op.create_unique_constraint(None, 'organizerphones', ['id'])
    op.add_column('periods', sa.Column('upper', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'periods', ['upper'])
    op.create_unique_constraint(None, 'periods', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'periods', type_='unique')
    op.drop_constraint(None, 'periods', type_='unique')
    op.drop_column('periods', 'upper')
    op.drop_constraint(None, 'organizerphones', type_='unique')
    op.drop_constraint(None, 'memeberstatuss', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    op.alter_column('event', 'published_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('event', 'is_active')
    op.drop_constraint(None, 'coordinates', type_='unique')
    # ### end Alembic commands ###
