"""Create new entities revision

Revision ID: c3eeb1807b88
Revises: e2589f35a94f
Create Date: 2025-04-15 18:40:09.328396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3eeb1807b88'
down_revision: Union[str, None] = 'e2589f35a94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('isFavorite', sa.Boolean(), nullable=True),
    sa.Column('organizer', sa.String(), nullable=True),
    sa.Column('organizer_address', sa.String(), nullable=True),
    sa.Column('organizer_address_eng', sa.String(), nullable=True),
    sa.Column('organizer_supervisor_fio', sa.String(), nullable=True),
    sa.Column('organizer_supervisor_fio_eng', sa.String(), nullable=True),
    sa.Column('organizer_site', sa.String(), nullable=True),
    sa.Column('organizer_vk', sa.String(), nullable=True),
    sa.Column('organizer_telegram', sa.String(), nullable=True),
    sa.Column('organizer_email', sa.String(), nullable=True),
    sa.Column('free_places', sa.Boolean(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_format', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('location_eng', sa.String(), nullable=True),
    sa.Column('registration_status', sa.String(), nullable=True),
    sa.Column('registration_period', sa.String(), nullable=True),
    sa.Column('registration_comment', sa.String(), nullable=True),
    sa.Column('place_number', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_eng', sa.String(), nullable=True),
    sa.Column('cypher', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('parent', sa.Boolean(), nullable=True),
    sa.Column('typeof', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('coordinates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude')
    )
    op.create_table('memeberstatuss',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('member_status_name', sa.String(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('member_status_name')
    )
    op.create_table('organizerphones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('periods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lower', sa.String(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('lower')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periods')
    op.drop_table('organizerphones')
    op.drop_table('memeberstatuss')
    op.drop_table('coordinates')
    op.drop_table('event')
    # ### end Alembic commands ###
