"""Change coordinates table structure

Revision ID: cde85cb21a27
Revises: 40950b5ee32e
Create Date: 2025-04-18 22:33:53.410941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde85cb21a27'
down_revision: Union[str, None] = '40950b5ee32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coordinates_id_key', 'coordinates', type_='unique')
    op.drop_constraint('coordinates_latitude_key', 'coordinates', type_='unique')
    op.drop_constraint('coordinates_longitude_key', 'coordinates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('coordinates_longitude_key', 'coordinates', ['longitude'])
    op.create_unique_constraint('coordinates_latitude_key', 'coordinates', ['latitude'])
    op.create_unique_constraint('coordinates_id_key', 'coordinates', ['id'])
    # ### end Alembic commands ###
